name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: '0 0 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
        rust: ["1.59", stable, beta, nightly]
    runs-on: ${{ matrix.os }}
    steps:
    - run: echo "triple=x86_64-unknown-linux-gnu" >> $GITHUB_ENV
      if: "${{ matrix.os == 'ubuntu-latest' }}"
    - run: echo "triple=x86_64-apple-darwin" >> $GITHUB_ENV
      if: "${{ matrix.os == 'macOS-latest' }}"
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    - name: build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: "--verbose"
    - name: doc
      uses: actions-rs/cargo@v1
      with:
        command: doc
        args: "--verbose"
    - name: build --release
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: "--verbose --release"
    - name: rustup component add rust-src
      run: "rustup component add rust-src --toolchain nightly-${{ env.triple }}"
      if: "${{ matrix.rust == 'nightly' }}"
    - name: ensure_no_std build
      run: "cargo +nightly build --verbose -Z build-std=core,panic_abort --target ${{ env.triple }} --release"
      working-directory: ensure_no_std
      if: "${{ matrix.rust == 'nightly' }}"
    - name: ensure_no_std run
      run: "./ensure_no_std/target/${{ env.triple }}/release/ensure_no_std"
      if: "${{ matrix.rust == 'nightly' }}"
    - name: outdated
      uses: actions-rs/cargo@v1
      with:
        command: outdated
        args: "--verbose --aggresssive --root-deps-only --exit-code 1"
    - name: rustup component add clippy
      run: "rustup component add clippy"
    - name: clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: "--verbose"
